version: '2'
services:
  mongo_db:
    image: 'mongo:3.4'
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'
    restart: always
  apii_host:
    image: 'webinnovate/leave-tracker-api'
    ports:
      - '4040:4040'
    depends_on:
      - mongo_db
    environment:
      - 'MONGO_HOST=mongodb://mongo_db:27017/leave_tracker'
      - MONGO_PORT=27017
    restart: always
  ui:
    image: 'webinnovate/leave-tracker-ui'
    depends_on:
      - apii_host
    ports:
      - '3000:3000'
    environment:
      - 'API_URL=http://localhost:4040/api/'
    restart: always